### ISSUE TITLE
Udp does not work?

### ISSUE THREAD

**Issue by sudhiaithal** [ansyun/dpdk-iperf#1]
I see that, UDP does not seem to work with dpdk_iperf

Server Started with : ./dpdk_iperf3 -s --bind 10.0.0.2 

Client with command ./iperf3 -c 10.0.0.2  -u -t 30 

I see the following error on server : 
Accepted connection from ::100:0:0:0, port 22685
iperf3: error - unable to accept stream connection: 

Is this known issue?

**Comment by bluenet13** [comment]
Please check dpdk_iperf code, why print such error.
UDP can work. we done that long time before, no record for it.

**Comment by Jerry-Tianchen** [comment]
It is not working. :) 
The function ANS recvfrom has a hardcoded "return -1".
I don't see how it will work.
