### ISSUE TITLE
 ans_mod_init: Assertion `0 == rc' failed.

### ISSUE THREAD

**Issue by msidana** [ansyun/dpdk-iperf#2]
I installed dpdk-iperf based on dpdk version 17.08. On starting dpdkiperf, I get an assertion failure.
Is there some kind of configuration/initialization needed. My hugepages are set and my interfaces are also binded to igb_uio module..

Please see logs below. Thanks for help.

root@dpdk-latest:~/dpdk-iperf# ./dpdk_iperf3 -s
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: Setting up physically contiguous memory...
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: Analysing 1995 files
EAL: Mapped segment 0 of size 0x200000
EAL: Mapped segment 1 of size 0x63400000
EAL: Mapped segment 2 of size 0x200000
EAL: Mapped segment 3 of size 0x95c00000
EAL: Mapped segment 4 of size 0x200000
EAL: TSC frequency is ~2399995 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=4df148c0;cpuset=[0])
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[-1] Can't find ans memzone 
dpdk_iperf3: src/ans_module.c:173: ans_mod_init: Assertion `0 == rc' failed.
Aborted (core dumped)
root@dpdk-latest:~/dpdk-iperf# ./dpdk_iperf3 -s --bind 41.0.41.22
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: Setting up physically contiguous memory...
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: Analysing 1995 files
EAL: Mapped segment 0 of size 0x200000
EAL: Mapped segment 1 of size 0x63400000
EAL: Mapped segment 2 of size 0x200000
EAL: Mapped segment 3 of size 0x95c00000
EAL: Mapped segment 4 of size 0x200000
EAL: TSC frequency is ~2399997 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=766188c0;cpuset=[0])
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[-1] Can't find ans memzone 
dpdk_iperf3: src/ans_module.c:173: ans_mod_init: Assertion `0 == rc' failed.
Aborted (core dumped)
root@dpdk-latest:~/dpdk-iperf#

**Comment by bluenet13** [comment]
You shall run ans(a user space tcp/ip stack ) before run dpdk-iperf.
By the way, you shall use 17.05.2 instead of 17.08

**Comment by msidana** [comment]
Thanks for the reply. I have done the setup again with dpdk 17.05.2.
Still getting error in running ans. Am I missing something ?

root@dpdk-latest:~/dpdk-ans/ans# ./build/ans -c 0xf -n 4 -- -p 0x1 --config="(0,0,2)"
EAL: Detected 4 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
EAL: PCI device 0000:00:04.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
EAL: PCI device 0000:00:05.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
param nb 1 ports 2 
port id 0 
 
Start to Init port 
	 port 0:  
	 port name net_virtio:  
	 max_rx_queues 1: max_tx_queues:1 
	 rx_offload_capa 0x1c: tx_offload_capa:0x0 
	 Creating queues: rx queue number=1 tx queue number=4... 
EAL: Error - exiting with code: 1
  Cause: Cannot configure device: err=-22, port=0
root@dpdk-latest:~/dpdk-ans/ans#

**Comment by msidana** [comment]
Thanks. I was able to run the server. But I am not able to start the client and getting Bad File desciptor error.
root@dpdk-latest:~/dpdk-iperf# ./dpdk_iperf3 -c 41.0.41.22
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: Setting up physically contiguous memory...
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: Analysing 1995 files
EAL: Mapped segment 0 of size 0x200000
EAL: Mapped segment 1 of size 0x63400000
EAL: Mapped segment 2 of size 0x200000
EAL: Mapped segment 3 of size 0x95c00000
EAL: Mapped segment 4 of size 0x200000
EAL: TSC frequency is ~2399997 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=4cdca8c0;cpuset=[0])
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[2] anssock app id: 14853 
USER8: LCORE[2] anssock app name: dpdk_iperf3 
USER8: LCORE[2] anssock app lcoreId: 2 
USER8: LCORE[2] mp ops number 4, mp ops index: 0 
fcntl(F_GETFL): Bad file descriptor



Server logs:
root@dpdk-latest:~/dpdk-iperf# ./dpdk_iperf3 -s --bind 41.0.41.22
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: Setting up physically contiguous memory...
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: Analysing 1995 files
EAL: Mapped segment 0 of size 0x200000
EAL: Mapped segment 1 of size 0x63400000
EAL: Mapped segment 2 of size 0x200000
EAL: Mapped segment 3 of size 0x95c00000
EAL: Mapped segment 4 of size 0x200000
EAL: TSC frequency is ~2399994 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=475198c0;cpuset=[0])
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[0] anssock app id: 14770 
USER8: LCORE[0] anssock app name: dpdk_iperf3 
USER8: LCORE[0] anssock app lcoreId: 0 
USER8: LCORE[0] mp ops number 4, mp ops index: 0 
USER8: LCORE[0] setsockopt: not support optname 2 
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------

**Comment by bluenet13** [comment]
ignore these error.
fcntl(F_GETFL): Bad file descriptor

**Comment by msidana** [comment]
Yes, but no TCP message exchange is happening between client and server. No traffic is getting initiated.

-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------

**Comment by bluenet13** [comment]
ans don't support loopback interface, so iperf client can't connec to the iperf server in the same ans.

**Comment by msidana** [comment]
I created a new machine for client. Now the client and server are running in two separate VMs. I am still getting the same issue.

-----------------SERVER----------------------
root@dpdk-latest:~/dpdk-iperf# ./dpdk_iperf3 -s --bind 41.0.41.22
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: Setting up physically contiguous memory...
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: Analysing 1995 files
EAL: Mapped segment 0 of size 0x200000
EAL: Mapped segment 1 of size 0x63400000
EAL: Mapped segment 2 of size 0x200000
EAL: Mapped segment 3 of size 0x95c00000
EAL: Mapped segment 4 of size 0x200000
EAL: TSC frequency is ~2399995 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=1d0918c0;cpuset=[0])
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[0] anssock app id: 17613 
USER8: LCORE[0] anssock app name: dpdk_iperf3 
USER8: LCORE[0] anssock app lcoreId: 0 
USER8: LCORE[0] mp ops number 4, mp ops index: 0 
USER8: LCORE[0] setsockopt: not support optname 2 
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------


--------------------CLIENT----------------------
root@manik-dpdk2:~/dpdk-iperf# ./dpdk_iperf3 -c 41.0.41.22
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: Setting up physically contiguous memory...
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: Analysing 1995 files
EAL: Mapped segment 0 of size 0x63c00000
EAL: Mapped segment 1 of size 0x200000
EAL: Mapped segment 2 of size 0x200000
EAL: Mapped segment 3 of size 0x95400000
EAL: Mapped segment 4 of size 0x200000
EAL: TSC frequency is ~2399995 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=3177e8c0;cpuset=[0])
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[0] anssock app id: 2267 
USER8: LCORE[0] anssock app name: dpdk_iperf3 
USER8: LCORE[0] anssock app lcoreId: 0 
USER8: LCORE[0] mp ops number 4, mp ops index: 0 
fcntl(F_GETFL): Bad file descriptor

**Comment by bluenet13** [comment]
Can you ping successfully from one vm to another vm which bind to dpdk?

**Comment by msidana** [comment]
I tried ping4 between the two VMs with the help of pktgen-dpdk. I could see the RX and TX counters increase.
After this, I tried again to run iperf-dpdk, but got the same issue of bad file descriptor.

**Comment by msidana** [comment]
I would also like to understand that since DPDK drivers are taking control of my ports, so I wont be able to use the usual ping command to resolve ARP and get ICMP ECHO REQUEST/REPLY. 

A) Does ANS, running as an application [./build/ans -c 0x2 -n 1 -- -p 0x1 --config="(0,0,1)"] would take care of resolving ARP when I run dpdk-iperf3 on top of it ?
OR
B) Is it handled by dpdk-iperf3 ?
OR 
C) Something else needs to be done ?

**Comment by bluenet13** [comment]
Do you configure 41.0.41.22 on ANS(tcp/ip STACK)?
share the ans startup log.

You can try ping 41.0.41.22 from you client vm, you don't use dpdk to bind your nic.

**Comment by msidana** [comment]
Yes, I configured 41.0.41.22 on ANS(tcp/ip STACK) on SERVER VM.
Configured 41.0.41.4 on ANS(tcp/ip STACK) on CLIENT VM.
Both these interfaces are binded to DPDK igb_uio.

I am able to ping between these two interfaces if I release them to kernel network stack.


This is my ans startup log on 40.0.41.22 (SERVER)

root@dpdk-latest:~/dpdk-ans/ans# ./build/ans -c 0x2 -n 1 -- -p 0x1 --config="(0,0,1)"
EAL: Detected 4 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
EAL: PCI device 0000:00:04.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
EAL: PCI device 0000:00:05.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
param nb 1 ports 2 
port id 0 
 
Start to Init port 
	 port 0:  
	 port name net_virtio:  
	 max_rx_queues 1: max_tx_queues:1 
	 rx_offload_capa 0x1c: tx_offload_capa:0x0 
	 Creating queues: rx queue number=1 tx queue number=1... 
	 MAC Address:FA:16:3E:99:AD:DB 
	 Deault-- tx pthresh:0, tx hthresh:0, tx wthresh:0, txq_flags:0xf00 
	 lcore id:1, tx queue id:0, socket id:0 
	 Conf-- tx pthresh:0, tx hthresh:0, tx wthresh:0, txq_flags:0x0 


Skipping disabled port 1
Allocated mbuf pool on socket 0, mbuf number: 16384 

Initializing rx queues on lcore 1 ... 
Default-- rx pthresh:0, rx hthresh:0, rx wthresh:0 
port id:0, rx queue id: 0, socket id:0 
Conf-- rx pthresh:8, rx hthresh:8, rx wthresh:4 

core mask: 2, sockets number:1, lcore number:1 
start to init ans 
USER8: LCORE[1] lcore mask 0x2 
USER8: LCORE[1] lcore id 1 is enable 
USER8: LCORE[1] lcore number 1 
USER1: rte_ip_frag_table_create: allocated of 25165952 bytes at socket 0
add veth0 device, kni id 0 
USER8: LCORE[1] Interface veth0 if_capabilities: 0x0 
add IP a000002 on device veth0 

Skipping disabled port 1
show all IPs: 

 veth0: mtu 1500 
	link/ether fa:16:3e:99:ad:db
 	inet addr: 10.0.0.2/24

add static route 

ANS IP routing table
 10.0.0.0/24 via dev veth0 src 10.0.0.2 
 10.10.0.0/24 via 10.0.0.5 dev veth0 


Checking link status done
Port 0 Link Up - speed 10000 Mbps - full-duplex
USER8: main loop on lcore 1
USER8:  -- lcoreid=1 portid=0 rxqueueid=0
nb ports 2 hz: 2400001639 





ANS start up logs on 41.0.41.4(CLIENT)

root@manik-dpdk2:~/dpdk-ans/ans# ./build/ans -c 0x2 -n 1 -- -p 0x1 --config="(0,0,1)"
EAL: Detected 4 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
EAL: PCI device 0000:00:04.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
param nb 1 ports 1 
port id 0 
 
Start to Init port 
	 port 0:  
	 port name net_virtio:  
	 max_rx_queues 1: max_tx_queues:1 
	 rx_offload_capa 0x1c: tx_offload_capa:0x0 
	 Creating queues: rx queue number=1 tx queue number=1... 
	 MAC Address:FA:16:3E:24:F6:3F 
	 Deault-- tx pthresh:0, tx hthresh:0, tx wthresh:0, txq_flags:0xf00 
	 lcore id:1, tx queue id:0, socket id:0 
	 Conf-- tx pthresh:0, tx hthresh:0, tx wthresh:0, txq_flags:0x0 

Allocated mbuf pool on socket 0, mbuf number: 16384 

Initializing rx queues on lcore 1 ... 
Default-- rx pthresh:0, rx hthresh:0, rx wthresh:0 
port id:0, rx queue id: 0, socket id:0 
Conf-- rx pthresh:8, rx hthresh:8, rx wthresh:4 

core mask: 2, sockets number:1, lcore number:1 
start to init ans 
USER8: LCORE[1] lcore mask 0x2 
USER8: LCORE[1] lcore id 1 is enable 
USER8: LCORE[1] lcore number 1 
USER1: rte_ip_frag_table_create: allocated of 25165952 bytes at socket 0
add veth0 device, kni id 0 
USER8: LCORE[1] Interface veth0 if_capabilities: 0x0 
add IP a000002 on device veth0 
show all IPs: 

 veth0: mtu 1500 
	link/ether fa:16:3e:24:f6:3f
 	inet addr: 10.0.0.2/24

add static route 

ANS IP routing table
 10.0.0.0/24 via dev veth0 src 10.0.0.2 
 10.10.0.0/24 via 10.0.0.5 dev veth0 


Checking link status done
Port 0 Link Up - speed 10000 Mbps - full-duplex
USER8: main loop on lcore 1
USER8:  -- lcoreid=1 portid=0 rxqueueid=0
nb ports 1 hz: 2399993412

**Comment by bluenet13** [comment]
where did you configure your IP? no 40.0.41.22 in ans. you shall anscli to configure to ans, not to linux kernel.

veth0: mtu 1500
link/ether fa:16:3e:24:f6:3f
inet addr: 10.0.0.2/24

add static route

ANS IP routing table
10.0.0.0/24 via dev veth0 src 10.0.0.2
10.10.0.0/24 via 10.0.0.5 dev veth0

**Comment by msidana** [comment]
Its working after configuring IP through anscli.
Thanks you so much for your help and support. :)

**Comment by bluenet13** [comment]
Study the doc(https://github.com/ansyun/dpdk-ans/tree/master/doc/guides) before you use it. :)
