### ISSUE TITLE
Observed negative values for retransmits

### ISSUE THREAD

**Issue by msidana** [ansyun/dpdk-iperf#3]
Hi,
While running a few tests on iperf3-dpdk for TCP, I observed a few negative values for "retransmits". Retransmits show the number of packets retransmitted due to some issue (ACK not received). Is it possible for it to have negative value (I don't have much idea on iperf implementation)?

Putting below a sample output where I observed this.
{
			"streams":	[{
					"socket":	2143,
					"start":	4.00003,
					"end":	5.00004,
					"seconds":	1.00002,
					"bytes":	278232504,
					"bits_per_second":	2.22582e+09,
					"retransmits":	-1,
					"snd_cwnd":	0,
					"rtt":	4320356,
					"omitted":	false
				}, {
					"socket":	2144,
					"start":	4.00003,
					"end":	5.00005,
					"seconds":	1.00002,
					"bytes":	268136296,
					"bits_per_second":	2.14505e+09,
					"retransmits":	-1,
					"snd_cwnd":	0,
					"rtt":	4320356,
					"omitted":	false
				}, {
					"socket":	2145,
					"start":	4.00004,
					"end":	5.00005,
					"seconds":	1.00002,
					"bytes":	303914928,
					"bits_per_second":	2.43128e+09,
					"retransmits":	-1,
					"snd_cwnd":	0,
					"rtt":	4320356,
					"omitted":	false
				}, {
					"socket":	2146,
					"start":	4.00004,
					"end":	5.00005,
					"seconds":	1.00001,
					"bytes":	173041792,
					"bits_per_second":	1.38432e+09,
					"retransmits":	-1,
					"snd_cwnd":	0,
					"rtt":	4320356,
					"omitted":	false
				}],
			"sum":	{
				"start":	4.00003,
				"end":	5.00004,
				"seconds":	1.00002,
				"bytes":	1023325520,
				"bits_per_second":	8.18647e+09,
				"retransmits":	-4,
				"omitted":	false

Thanks for help.

**Comment by msidana** [comment]
Putting another output (non-json). Seems there is some issue due to overflow (4294967294) while taking the sum

[2149]   5.00-6.00   sec  63.3 MBytes   531 Mbits/sec  4294967294   0.00 Bytes       
[2150]   5.00-6.00   sec   289 MBytes  2.42 Gbits/sec  4294967294   0.00 Bytes       
[2151]   5.00-6.00   sec   290 MBytes  2.43 Gbits/sec  4294967294   0.00 Bytes       
[2152]   5.00-6.00   sec   290 MBytes  2.43 Gbits/sec  4294967294   0.00 Bytes       
[SUM]   5.00-6.00   sec   931 MBytes  7.81 Gbits/sec   -8

**Comment by bluenet13** [comment]
could you debug dpdk-iperf and fix it?

**Comment by msidana** [comment]
I see a lot of differences between the latest iperf3 code and the iperf-3.1.3 used here. Do you have any plans of merging the latest changes of iperf3 with ANS dpdk-iperf ?

**Comment by bluenet13** [comment]
No  time to do that . Very welcome if you can do it. -:)

**Comment by bluenet13** [comment]
fix it in the latest ans version.
