### ISSUE TITLE
dpdk-iperf3 performance

### ISSUE THREAD

**Issue by Luo-Liang** [ansyun/dpdk-iperf#4]
Hi! 

I'm trying out ansyun on EC2 C5.18xlarge instances in a placement group.

I ran dpdk-iperf using the following command:

`sudo $RTE_ANS/ans/build/ans -c 0x7 -n 1  -- -p 0x1 --config="(0,0,1)" --enable-kni --enable-ipsync --enable-jumbo --max-pkt-len 9001 &`

I also changed `MAX_TX_BURST` in ans_main.h from 32 to 1 according to suggestion here 
https://github.com/ansyun/dpdk-ans/issues/16

I then ran dpdk-iperf3 like this:
`sudo ./dpdk_iperf3 -s --bind 172.31.5.23 `
` sudo ./dpdk_iperf3  -c 172.31.5.23 --bind 172.31.15.49 `

Here is the result I get:

Streams Cnt | Baseline Linux | DPDK-ans
-- | -- | --
1 | 9.89 | 9.59
2 | 19.8 | 9.67
3 | 25.5 | 9.67
4 | 23.9 | 9.67

I would like to know if there's any parameters to tune, since it seems like ansyun cannot give more than 10Gbps bandwidth?

**Comment by bluenet13** [comment]
What is your NIC type ? 40g NIC?

**Comment by Luo-Liang** [comment]
25g NIC

**Comment by bluenet13** [comment]
maybe the traffic Streams locate on one core.

**Comment by Luo-Liang** [comment]
Do you know how we make stream on different cores, other than launch many dpdk_iperf instances? Does that also mean a single core can only process 9.59Gbps packets?

**Comment by bluenet13** [comment]
Fix it in the latest ans version.
