### ISSUE TITLE
Issue Connecting Client to Server (Separate Hosts)

### ISSUE THREAD

**Issue by austin-millan** [ansyun/dpdk-iperf#6]
Hi,

I am trying to run dpdk-iperf client and server on different host over DPDK ports. I am running dpdk-ans on both hosts, and have used `anscli` to configure the dev `veth0` IPs as well.

Attempting to connect `dpdk-iperf` from client's DPDK port 0 to server's DPDK port 0.

However when I attempt to run the server or client with the assigned IP for the DPDK port, I get the error 102 (IELISTEN). 

## Server

10.19.0.239 is DPDK port 0 on server

```
ans> ip addr add 10.19.0.239/32 dev veth0
Add IP address successfully 
```

```
# ./iperf3 -s --bind 10.19.0.239
iperf3: error - unable to start listener for connections: Cannot assign requested address
...
iperf3: too many errors, exiting
```

## Client

10.19.0.33 is DPDK port 0 on client

```
ans> ip addr add 10.19.0.33/32 dev veth0
Add IP address successfully 
```

## Ping Server Success

I am able to ping server's DPDK port 0 using regular ping and DPDK's ping4. 

```
ping 10.19.0.239
PING 10.19.0.239 (10.19.0.239) 56(84) bytes of data.
64 bytes from 10.19.0.239: icmp_seq=1 ttl=64 time=0.203 ms
64 bytes from 10.19.0.239: icmp_seq=2 ttl=64 time=0.180 ms
```

I noticed a log on server ANS write the following:

```
USER8: LCORE[1] Neigh IP address(0xa1300ef) already exist, error code 1 
```

```
ans> ip stats show
 Total packets received               :2 
 ...
 Datagrams delivered to upper level   :2 
 Total ip packets generated here      :2 
...
```

Any help would be appreciated. `dpdk-iperf` works between client/server if I do not use DPDK ports.

**Comment by bluenet13** [comment]
You shall change your netmask as 24.
ip addr add 10.19.0.33/24 dev veth0

**Comment by austin-millan** [comment]
Yes I have tried that also.

```
ans> ip addr del 10.0.0.2/24 dev veth0
Del IP address successfully 
ans> ip addr add 10.19.0.239/24 dev veth0
Add IP address successfully
```

```
# /usr/src/dpdk-iperf/iperf3 -s --bind 10.19.0.239
iperf3: error - unable to start listener for connections: Cannot assign requested address'
...
iperf3: too many errors, exiting
```

edit: `dpdk-iperf` server can bind to the IP for a DPDK port, right?

**Comment by austin-millan** [comment]
So sorry, I was running `iperf3` instead of `dpdk_iperf3`.

Here's using `dpdk_iperf3`

## Server
```
/usr/src/dpdk-iperf/dpdk_iperf3 -s --bind 10.19.0.239 -d
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket_15061_e4ee4dedc192
EAL: Probing VFIO support...
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[0] anssock app id: 15061 
USER8: LCORE[0] anssock app name: dpdk_iperf3 
USER8: LCORE[0] anssock app lcoreId: 0 
USER8: LCORE[0] mp ops number 4, mp ops index: 0 
USER8: LCORE[0] setsockopt: not support optname 2 
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

## Client
```
 /usr/src/dpdk-iperf/dpdk_iperf3 -c 10.19.0.239 -p 5201
EAL: Detected 2 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket_31292_39d0bdcbb2066
EAL: Probing VFIO support...
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[0] anssock app id: 31292 
USER8: LCORE[0] anssock app name: dpdk_iperf3 
USER8: LCORE[0] anssock app lcoreId: 0 
USER8: LCORE[0] mp ops number 4, mp ops index: 0 
iperf3: error - unable to connect to server:
```

**Comment by austin-millan** [comment]
I should note that I am using DPDK 18.11 here...

**Comment by FBryczak** [comment]
@austin-millan , hello, were you able to solve your problem? I'm having the same issue here, same DPDK version. Using ANS on AWS VMs I'm able to ping from both sides but dpdk_iperf3 fails....

**Comment by austin-millan** [comment]
@FBryczak wow, didn't realize this issue was still open after all this time.

But no I didn't get this working. Maybe it was a overestimation of what DPDK ANS provides. I was also running on AWS and that may be the issue. Could try baremetal hosts connected over ethernet.

**Comment by FBryczak** [comment]
@austin-millan hi :)  it turned out that using -B on both client and server to explicitly bind to the only ANS interface I've had did it for me. Before that I have tried the ".rxmode = {.offloads = .." fix in ans_main.c as mentioned on slide 20 in https://www.youtube.com/watch?v=NYthZ8GYCHM&ab_channel=DPDKProject but it didn't matter.
Cheers!

**Comment by austin-millan** [comment]
@FBryczak So you're saying you must bind to the ANS interface on both server and client for it to work when there's a switch between the hosts?

**Comment by FBryczak** [comment]
@austin-millan , not sure if that has anything to do with a presence of a switch (of lack thereof as i'm not sure what's underneath, this is AWS i'm using), but when I added -B <ANS_IP> to dpdk_iperf3 on both sides (different ANS_IPs obviously) then both sides were able to connect. My config is two EC2 instances in a cluster placement group with ANS on top of DPDK v18.11.

**Comment by austin-millan** [comment]
@FBryczak Thank you for getting back to me. This answers my question so I'm closing the issue. Glad you were able to get it working!
